### ISSUE TITLE
port to psvita homebrew for henkaku users

### ISSUE THREAD

**Issue by jcmejia** [STJr/SRB2#177]
please port to psvita users on 3.60 can run hombrew

**Comment by MonsterIestyn** [comment]
No idea if anyone on our team knows anything about porting to psvita sorry

**Comment by toasterone** [comment]
It has been exactly one year since this issue was opened, and in that time we have officially made the decision to only support Windows, Mac OS X\*, and Linux ~~(and DOS for fun sometimes)~~. It would very much be nice to support additional platforms, but there is only so much capacity the development team has for maintaining this game.

I will also note that I don't actually believe anybody on the development team owns a Vita, further complicating this.

_\*no developers on the team currently have a device running this operating system, but this repository does have a buildbot which provides workable builds and tells us if we introduce failing changes._
