### ISSUE TITLE
port to android

### ISSUE THREAD

**Issue by jcmejia** [STJr/SRB2#178]
please port to android

**Comment by Voros2** [comment]
You may want to contact beloko, the developer of Doom Touch. He successfully ported GZDoom, PrBoom+, Chocolate Doom, Doom Retro (coming soon in Delta Touch, Doom Touch's successor), Chocolate Strife, Quake 1, etc. and with a simple and precise control scheme.

**Comment by jcmejia** [comment]
Ok thanks just did

**Comment by MonsterIestyn** [comment]
Sorry for taking so long to respond, but I should note SRB2 is based on an old version of Doom Legacy, so it may not be quite the same as porting all those versions/ports of Doom. Would be cool if someone did port our game to android though.

**Comment by jcmejia** [comment]
Yeah really wish someone could port srb2 to Android would be cool

**Comment by toasterone** [comment]
It has been exactly one year since this issue was opened, and in that time we have officially made the decision to only support Windows, Mac OS X\*, and Linux ~~(and DOS for fun sometimes)~~. It would very much be nice to support additional platforms, but there is only so much capacity the development team has for maintaining this game.

Android is absolutely a platform we have interest in, and we wouldn't say no to an outsider coming in to sort this out, but we're just hobbyists without the aptitude for a task so large. Thank you for your interest, and apologies for not being able to deliver.

_\*no developers on the team currently have a device running this operating system, but this repository does have a buildbot which provides workable builds and tells us if we introduce failing changes._
