### ISSUE TITLE
srb2

### ISSUE THREAD

**Issue by symbios24** [STJr/SRB2#204]
Hello, sonic robo blast2 installation is broken in retropie ,installation fails with a message about a file is not been found

can this be fixed?

thanks

**Comment by MonsterIestyn** [comment]
Sorry about us taking so long to respond, we've been busy! As far as I'm aware, we SRB2 devs haven't tested SRB2 on retropie ourselves, though retropie's own forums have a thread on SRB2:

https://retropie.org.uk/forum/topic/9529/sonic-robo-blast-2

Would be a good idea to check there perhaps; it appears they encountered the same problem (or something similar), but managed to fix it eventually. Or at least it looks like it, anyway.

**Comment by toasterone** [comment]
It's been almost a year since this issue was opened. As there has been no further movement with regards to this, I believe the matter has been reasonably settled and as such I am closing this.

A reminder to future individuals exploring the issue history - SRB2 on retropie is not officially supported by us. Despite our repository containing several different ports, due to the limited resources/interest of our development team we only actively support Windows, Mac OS X\*, and Linux ~~(and DOS for fun sometimes)~~.

_\*no developers on the team currently have a device running this operating system, but this repository does have a buildbot which provides workable builds and tells us if we introduce failing changes._

**Comment by symbios24** [comment]
its working ok since a few months thanks
