### ISSUE TITLE
Need to extend the disclaimers...

### ISSUE THREAD

**Issue by Sslaxx** [STJr/SRB2#247]
...to include:

- id Software LLC (DOOM source code);
- Doom Legacy developers

These should be in README.MD, at the very least.

**Comment by toasterone** [comment]
We acknowledge id Software and the Doom Legacy developers:
- at the top of every source file which was inherited through them; for example, check out the top of p_setup.c
- in the game's credits (stored as a string in f_finale.c)

In addition, the disclaimer in README.MD is predominantly to provide a safeguard against SEGA, which is not mentioned elsewhere in the repository (but is on our website and in the game's quit screen asset).

Given this information, do you still believe updating README.MD is necessary?

**Comment by toasterone** [comment]
It's been over a month since I originally responded to this issue, several times the length of time between your posting and my comment. Since you have not responded, I am closing this issue. If you feel this is an inappropriate response, you are welcome to open another issue - but I believe the matter as described is reasonably settled.
