### ISSUE TITLE
1440 and 4k resolutions do not appear in settings menu

### ISSUE THREAD

**Issue by psypherium** [STJr/SRB2#287]
1440 and 4k resolutions do not appear in settings menu

I can select 1920 x 1200 but nothing greater.

Changing resolutions on a 1440p screen work fine, although the full resolution is not available

Changing resolutions on a 2160p screen does not seem to function, I select a resolution which should give black bars on either side, but no black bars appear, it seems to actually be running at 2160p regardless of which setting I select.

Some strange issues :S

**Comment by monster-psychic-cat** [comment]
Probably not exactly what you want, but I've recently made [a branch](https://github.com/monster-psychic-cat/SRB2/tree/ultrahd)  that supports up to the **10K** resolution (10240x4320), also including basic 16:9 **8K** (7680x4320), **4K** (3840x2160) and **2K** (2160x1080) resolutions. _Very_ experimental, not guaranteed to be fast or even display.

**Comment by toasterone** [comment]
Apologies for the delay. I am no longer a developer for this game, but I can offer some explanation.

The game has a software renderer which, being mostly written in 1993 for DooM, works off a pre-initialised array instead of being runtime-allocated. The size of this array is limited to `1920*1200` (the maximum you have identified), in order to not take up too much memory in practice. It is possible to increase this by modifying the code, but the game already struggles in performing when pushing that many pixels, so the developers chose to limit it to the conventional "HD" reslolution's nearest multiple of `320*200` and have seen no reason to modify it before now.

One silver lining is that this game, when being run in "windowed fullscreen", does not cause any negative side effects when run in a lower resolution like messing with your OS's resolution. In addition, it is actively designed around being run in resolutions that were popular during the late 90's, with no extremely fine details lost by running at, say, `1280*800`.

I won't close the issue because I'm not involved in decision-making processes anymore, but knowing the current status of the team, you should know that it is unlikely these resolutions will be supported in the foreseeable future.
